### ISSUE TITLE
variable mu_update_interval is not used

### ISSUE THREAD

**Issue by ReDeiPirati** [JianGoForIt/YellowFin#10]
The `mu_update_interval` parameters is not used by the [optimizer](https://github.com/JianGoForIt/YellowFin/blob/master/tuner_utils/yellowfin.py#L18), is it declared for future works? Maybe to schedule the mu during training?

**Comment by JianGoForIt** [comment]
Right. It is for potential future work and currently dummy argument.

**Comment by ReDeiPirati** [comment]
Thank you, i close!
