### ISSUE TITLE
Potentially dead tf.assert Op

### ISSUE THREAD

**Issue by ilya-edrenkin** [JianGoForIt/YellowFin#12]
It seems that there is an assert operation which might never be evaluated:
` tf.assert_equal(tf.size(root), tf.constant(1) )`
https://github.com/JianGoForIt/YellowFin/blob/master/tuner_utils/yellowfin.py#L180

Newer versions of TF produce an error with that, and it was probably not the intended behaviour.

Related issue: https://github.com/tensorflow/tensorflow/issues/11315

**Comment by JianGoForIt** [comment]
@ilya-edrenkin Thanks for the detailed information. We have fixed this in master branch.
