### ISSUE TITLE
Change license approval to integrate YF in T2T

### ISSUE THREAD

**Issue by ReDeiPirati** [JianGoForIt/YellowFin#16]
@JianGoForIt  as i said in different issues i was trying to adapt `YF` to be usable in [tensor2tensor]( https://github.com/tensorflow/tensor2tensor) and after my PR to definitively integrate YF in T2T, it raised a license problem. Once the PR is accepted it will override your MIT License, so the T2T authors need your OK(approval) to keep the PR, otherwise we cannot use your code. This is the [PR](https://github.com/tensorflow/tensor2tensor/pull/141).

**Comment by JianGoForIt** [comment]
Hi @ReDeiPirati 

Please go ahead and override the license. I have checked it up with all collaborators and we are all happy with it.

Cheers
