### ISSUE TITLE
`lr` vs `learning_rate`

### ISSUE THREAD

**Issue by rasbt** [JianGoForIt/YellowFin#3]
Just gave yellowfin a try yesterday and it works nicely! Just a minor comment/suggestion:

what do you think about renaming `lr` to `learning_rate` for consistency with other tensorflow optimizers. Can open a small PR

**Comment by JianGoForIt** [comment]
Thanks @rasbt for pointing out. We will consider this in later cleaning-up stage.

**Comment by JianGoForIt** [comment]
Hi @rasbt, we have updated the argument name. Please check it out.

**Comment by rasbt** [comment]
Oh cool, that was quick! Thanks!
