### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by rasbt** [JianGoForIt/YellowFin#4]
Thanks for sharing the yellowfin code on github, I just tried it out in one of my projects and got good results. I am just wondering if you are planning to add a open source license in future so that people can use it (of course with proper acknowledgement) in their projects and don't have to remove the yellowfin code sections when sharing their projects e.g., on GitHub.

**Comment by mitliagkas** [comment]
Thank you for trying our optimizer! We are more than happy to share. We will add a permissive license in the next couple of days.

**Comment by rasbt** [comment]
Nice, thanks!

**Comment by JianGoForIt** [comment]
Hey @rasbt, I added an MIT license. Please feel free to include our code and cite our paper as well.

**Comment by rasbt** [comment]
Awesome, thanks! 

> Please feel free to

If I am publishing the outcome of my project later this year and YellowFin will be part of it, I will cite your paper of course! :)
